name: my_discount
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.2.2+20

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  another_flushbar: ^1.10.18
  app_settings: ^4.1.1
  cupertino_icons: ^1.0.2
  device_info: ^2.0.0
  equatable: ^2.0.3
  firebase_analytics: ^8.0.0
  firebase_core: ^1.3.0
  firebase_crashlytics: ^2.0.0
  firebase_messaging: ^10.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_facebook_auth: ^3.5.0
  flutter_html: ^2.0.0-nullsafety.0
  flutter_image_compress: ^1.0.0
  flutter_local_notifications: ^5.0.0+1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^4.2.0
  flutter_svg: ^0.21.0+1
  font_awesome_flutter: ^9.0.0
  get_it: ^6.1.1
  google_sign_in: ^5.0.2
  hive: ^2.0.3
  hive_flutter: ^1.0.0
  http: ^0.13.1
  image_picker: ^0.7.0
  international_phone_input:
    git: https://github.com/CristeaIon/flutter-international-phone-input.git
  internet_connection_checker: ^0.0.1
  is_service:
    git: https://github.com/CristeaIon/is_service.git
  material_design_icons_flutter: ^5.0.5955-rc.1
  package_info: ^2.0.0
  path_provider: ^2.0.2
  permission_handler: ^8.1.4+2
  provider: ^5.0.0
  qr_code_scanner: ^0.4.0
  qr_flutter: ^4.0.0
  shared_preferences: ^2.0.6
  sign_in_with_apple: ^3.0.0
  simple_html_css: ^3.0.1
  sms_autofill: ^2.0.0
  url_launcher: ^6.0.3

dev_dependencies:
  build_runner: ^1.10.6
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.1
  injectable_generator: ^1.2.2
  mockito: ^5.0.4
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - lang/
  # fonts:
  # - family: MyFlutterApp
  # fonts:
  #   - asset: fonts/MyFlutterApp.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
