// Mocks generated by Mockito 5.0.4 from annotations
// in my_discount/test/unit_test/infrastucture/is_service_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;
import 'dart:ui' as _i12;

import 'package:is_service/service_client_response.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:my_discount/aplication/providers/news_settings.dart' as _i11;
import 'package:my_discount/core/formater.dart' as _i16;
import 'package:my_discount/core/internet_connection_service.dart' as _i13;
import 'package:my_discount/domain/data_source/remote_datasource.dart' as _i17;
import 'package:my_discount/domain/entities/card.dart' as _i8;
import 'package:my_discount/domain/entities/company_model.dart' as _i9;
import 'package:my_discount/domain/entities/news_model.dart' as _i7;
import 'package:my_discount/domain/entities/profile_model.dart' as _i2;
import 'package:my_discount/domain/entities/tranzaction_model.dart' as _i10;
import 'package:my_discount/domain/entities/user_model.dart' as _i3;
import 'package:my_discount/domain/repositories/is_service_repository.dart'
    as _i5;
import 'package:my_discount/domain/repositories/local_repository.dart' as _i15;
import 'package:my_discount/infrastructure/core/remote_config_service.dart'
    as _i14;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeProfile extends _i1.Fake implements _i2.Profile {}

class _FakeUser extends _i1.Fake implements _i3.User {}

class _FakeIsResponse extends _i1.Fake implements _i4.IsResponse {}

/// A class which mocks [IsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIsService extends _i1.Mock implements _i5.IsService {
  MockIsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i7.News>> getAppNews() =>
      (super.noSuchMethod(Invocation.method(#getAppNews, []),
              returnValue: Future<List<_i7.News>>.value(<_i7.News>[]))
          as _i6.Future<List<_i7.News>>);
  @override
  _i6.Future<_i2.Profile> getClientInfo({String? id, int? registerMode}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getClientInfo, [], {#id: id, #registerMode: registerMode}),
              returnValue: Future<_i2.Profile>.value(_FakeProfile()))
          as _i6.Future<_i2.Profile>);
  @override
  _i6.Future<_i3.User> updateClientInfo({Map<String, dynamic>? json}) => (super
          .noSuchMethod(Invocation.method(#updateClientInfo, [], {#json: json}),
              returnValue: Future<_i3.User>.value(_FakeUser()))
      as _i6.Future<_i3.User>);
  @override
  _i6.Future<_i4.IsResponse> requestActivationCard(
          {Map<String, dynamic>? json}) =>
      (super.noSuchMethod(
              Invocation.method(#requestActivationCard, [], {#json: json}),
              returnValue: Future<_i4.IsResponse>.value(_FakeIsResponse()))
          as _i6.Future<_i4.IsResponse>);
  @override
  _i6.Future<List<_i8.DiscountCard>> getRequestActivationCards(
          {String? id, int? registerMode}) =>
      (super.noSuchMethod(
              Invocation.method(#getRequestActivationCards, [],
                  {#id: id, #registerMode: registerMode}),
              returnValue:
                  Future<List<_i8.DiscountCard>>.value(<_i8.DiscountCard>[]))
          as _i6.Future<List<_i8.DiscountCard>>);
  @override
  _i6.Future<List<_i9.Company>> getCompanyList() =>
      (super.noSuchMethod(Invocation.method(#getCompanyList, []),
              returnValue: Future<List<_i9.Company>>.value(<_i9.Company>[]))
          as _i6.Future<List<_i9.Company>>);
  @override
  _i6.Future<String> getTempId() =>
      (super.noSuchMethod(Invocation.method(#getTempId, []),
          returnValue: Future<String>.value('')) as _i6.Future<String>);
  @override
  _i6.Future<List<_i10.Transaction>> getTransactionList() =>
      (super.noSuchMethod(Invocation.method(#getTransactionList, []),
              returnValue:
                  Future<List<_i10.Transaction>>.value(<_i10.Transaction>[]))
          as _i6.Future<List<_i10.Transaction>>);
  @override
  _i6.Future<String> validatePhone({String? phone}) => (super.noSuchMethod(
      Invocation.method(#validatePhone, [], {#phone: phone}),
      returnValue: Future<String>.value('')) as _i6.Future<String>);
}

/// A class which mocks [IsResponse].
///
/// See the documentation for Mockito's code generation for more information.
class MockIsResponse extends _i1.Mock implements _i4.IsResponse {
  MockIsResponse() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [NewsSettings].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewsSettings extends _i1.Mock implements _i11.NewsSettings {
  MockNewsSettings() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isActivate =>
      (super.noSuchMethod(Invocation.getter(#isActivate), returnValue: false)
          as bool);
  @override
  set isActivate(bool? value) =>
      super.noSuchMethod(Invocation.setter(#isActivate, value),
          returnValueForMissingStub: null);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i6.Future<bool> getNewsState() =>
      (super.noSuchMethod(Invocation.method(#getNewsState, []),
          returnValue: Future<bool>.value(false)) as _i6.Future<bool>);
  @override
  void addListener(_i12.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i12.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}

/// A class which mocks [NetworkConnection].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkConnection extends _i1.Mock implements _i13.NetworkConnection {
  MockNetworkConnection() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i6.Future<bool>);
}

/// A class which mocks [RemoteConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteConfigService extends _i1.Mock
    implements _i14.RemoteConfigService {
  MockRemoteConfigService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String> getServiceNameFromRemoteConfig() => (super.noSuchMethod(
      Invocation.method(#getServiceNameFromRemoteConfig, []),
      returnValue: Future<String>.value('')) as _i6.Future<String>);
}

/// A class which mocks [LocalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalRepository extends _i1.Mock implements _i15.LocalRepository {
  MockLocalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void saveNewsLocal(List<dynamic>? newsList) =>
      super.noSuchMethod(Invocation.method(#saveNewsLocal, [newsList]),
          returnValueForMissingStub: null);
  @override
  List<_i7.News> getLocalNews() =>
      (super.noSuchMethod(Invocation.method(#getLocalNews, []),
          returnValue: <_i7.News>[]) as List<_i7.News>);
  @override
  String readEldestNewsId() =>
      (super.noSuchMethod(Invocation.method(#readEldestNewsId, []),
          returnValue: '') as String);
  @override
  List<_i7.News> deleteNews() =>
      (super.noSuchMethod(Invocation.method(#deleteNews, []),
          returnValue: <_i7.News>[]) as List<_i7.News>);
  @override
  _i6.Future<List<_i9.Company>> getSavedCompany(String? pattern) =>
      (super.noSuchMethod(Invocation.method(#getSavedCompany, [pattern]),
              returnValue: Future<List<_i9.Company>>.value(<_i9.Company>[]))
          as _i6.Future<List<_i9.Company>>);
  @override
  void saveCompanyListLocal(List<_i9.Company>? list) =>
      super.noSuchMethod(Invocation.method(#saveCompanyListLocal, [list]),
          returnValueForMissingStub: null);
  @override
  List<_i9.Company> searchCompany(String? pattern) =>
      (super.noSuchMethod(Invocation.method(#searchCompany, [pattern]),
          returnValue: <_i9.Company>[]) as List<_i9.Company>);
  @override
  _i6.Future<Map<String, dynamic>> returnProfileMapDataAsMap(
          _i2.Profile? profile) =>
      (super.noSuchMethod(
              Invocation.method(#returnProfileMapDataAsMap, [profile]),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i6.Future<Map<String, dynamic>>);
  @override
  _i2.Profile saveClientInfoLocal(_i2.Profile? profile) =>
      (super.noSuchMethod(Invocation.method(#saveClientInfoLocal, [profile]),
          returnValue: _FakeProfile()) as _i2.Profile);
  @override
  _i2.Profile getLocalClientInfo() =>
      (super.noSuchMethod(Invocation.method(#getLocalClientInfo, []),
          returnValue: _FakeProfile()) as _i2.Profile);
  @override
  _i3.User saveUserLocal(_i3.User? user) =>
      (super.noSuchMethod(Invocation.method(#saveUserLocal, [user]),
          returnValue: _FakeUser()) as _i3.User);
  @override
  void deleteLocalUser() =>
      super.noSuchMethod(Invocation.method(#deleteLocalUser, []),
          returnValueForMissingStub: null);
  @override
  _i3.User getLocalUser() =>
      (super.noSuchMethod(Invocation.method(#getLocalUser, []),
          returnValue: _FakeUser()) as _i3.User);
  @override
  Map<String, dynamic> returnUserMapToSave(Map<String, dynamic>? json) =>
      (super.noSuchMethod(Invocation.method(#returnUserMapToSave, [json]),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
  @override
  bool smsCodeVerification(String? serverCode, String? userCode) =>
      (super.noSuchMethod(
          Invocation.method(#smsCodeVerification, [serverCode, userCode]),
          returnValue: false) as bool);
}

/// A class which mocks [Formater].
///
/// See the documentation for Mockito's code generation for more information.
class MockFormater extends _i1.Mock implements _i16.Formater {
  MockFormater() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<Map<String, dynamic>> deleteImageFormatAndDecode(
          List<dynamic>? list, String? index) =>
      (super.noSuchMethod(
          Invocation.method(#deleteImageFormatAndDecode, [list, index]),
          returnValue: <Map<String, dynamic>>[]) as List<Map<String, dynamic>>);
  @override
  List<dynamic> parseDateTime(List<dynamic>? list, String? index) =>
      (super.noSuchMethod(Invocation.method(#parseDateTime, [list, index]),
          returnValue: <dynamic>[]) as List<dynamic>);
  @override
  Map<String, dynamic> splitDisplayName(Map<dynamic, dynamic>? map) =>
      (super.noSuchMethod(Invocation.method(#splitDisplayName, [map]),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
  @override
  _i6.Future<Map<String, dynamic>> downloadProfileImageOrDecodeString(
          Map<String, dynamic>? map) =>
      (super.noSuchMethod(
              Invocation.method(#downloadProfileImageOrDecodeString, [map]),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i6.Future<Map<String, dynamic>>);
  @override
  Map<String, dynamic> addToProfileMapSignMethod(
          Map<String, dynamic>? map, int? registerMode) =>
      (super.noSuchMethod(
          Invocation.method(#addToProfileMapSignMethod, [map, registerMode]),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
  @override
  List<dynamic> checkCompanyLogo(List<dynamic>? list) =>
      (super.noSuchMethod(Invocation.method(#checkCompanyLogo, [list]),
          returnValue: <dynamic>[]) as List<dynamic>);
}

/// A class which mocks [RemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDataSource extends _i1.Mock implements _i17.RemoteDataSource {
  MockRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.IsResponse> getRequest(String? urlFragment) =>
      (super.noSuchMethod(Invocation.method(#getRequest, [urlFragment]),
              returnValue: Future<_i4.IsResponse>.value(_FakeIsResponse()))
          as _i6.Future<_i4.IsResponse>);
  @override
  _i6.Future<_i4.IsResponse> postRequest(
          {Map<String, dynamic>? json, String? urlFragment}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #postRequest, [], {#json: json, #urlFragment: urlFragment}),
              returnValue: Future<_i4.IsResponse>.value(_FakeIsResponse()))
          as _i6.Future<_i4.IsResponse>);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i3.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(Invocation.getter(#id), returnValue: '') as String);
  @override
  String get accessToken =>
      (super.noSuchMethod(Invocation.getter(#accessToken), returnValue: '')
          as String);
  @override
  int get registerMode =>
      (super.noSuchMethod(Invocation.getter(#registerMode), returnValue: 0)
          as int);
  @override
  bool get isEmpty =>
      (super.noSuchMethod(Invocation.getter(#isEmpty), returnValue: false)
          as bool);
  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(Invocation.method(#toJson, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
}
