// Mocks generated by Mockito 5.0.7 from annotations
// in my_discount/test/unit_test/infrastucture/remote_data_source_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:is_service/service_client_response.dart' as _i2;
import 'package:is_service/src/service_client.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:my_discount/infrastructure/core/internet_connection_service.dart' as _i3;
import 'package:my_discount/domain/data_source/remote_datasource.dart' as _i7;


// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

class _FakeIsResponse extends _i1.Fake implements _i2.IsResponse {}

/// A class which mocks [NetworkConnection].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkConnection extends _i1.Mock implements _i3.NetworkConnection {
  MockNetworkConnection() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
}

/// A class which mocks [ServiceClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockServiceClient extends _i1.Mock implements _i5.ServiceClient {
  MockServiceClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.IsResponse> get(dynamic uri) =>
      (super.noSuchMethod(Invocation.method(#get, [uri]),
              returnValue: Future<_i2.IsResponse>.value(_FakeIsResponse()))
          as _i4.Future<_i2.IsResponse>);
  @override
  _i4.Future<_i2.IsResponse> post(dynamic uri, dynamic json) =>
      (super.noSuchMethod(Invocation.method(#post, [uri, json]),
              returnValue: Future<_i2.IsResponse>.value(_FakeIsResponse()))
          as _i4.Future<_i2.IsResponse>);
}

/// A class which mocks [RemoteConfigService]

/// A class which mocks [RemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDataSource extends _i1.Mock implements _i7.RemoteDataSource {
  MockRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.IsResponse> getRequest(String? urlFragment) =>
      (super.noSuchMethod(Invocation.method(#getRequest, [urlFragment]),
              returnValue: Future<_i2.IsResponse>.value(_FakeIsResponse()))
          as _i4.Future<_i2.IsResponse>);
  @override
  _i4.Future<_i2.IsResponse> postRequest(
          {Map<String, dynamic>? json, String? urlFragment}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #postRequest, [], {#json: json, #urlFragment: urlFragment}),
              returnValue: Future<_i2.IsResponse>.value(_FakeIsResponse()))
          as _i4.Future<_i2.IsResponse>);
}
